apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-preview" .Values.authService.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.authService.name }}
  ports:
    - port: {{ .Values.authService.servicePort }}
      targetPort: {{ .Values.authService.serviceTargetPort }}
  type: {{ .Values.authService.serviceType }}
{{- end }}
